micronaut:
  application:
    name: pixKeymanagerGrpc
datasources:
  default:
    url: jdbc:mysql://localhost:3306/pix_keymanager_grpc_db
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    schema-generate: CREATE_DROP
    dialect: MYSQL
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl.auto: update
